version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASS: qw123321
    ports: 
      - "172.16.201.1:5432:5432"
    networks:
      - migration_showcase
    volumes:
        - "service_db:/var/lib/postgresql"
        - "./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"


networks:
  migration_showcase:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.16.201.0/24"

volumes:
  service_db:
    driver: local