# Generated by Django 3.0 on 2019-12-17 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.TextField(choices=[('review', 'review'), ('published', 'published')], default='published'),
        ),
    ]
