# Generated by Django 3.0 on 2019-12-17 22:03

from django.db import migrations

from showcase.models import Post


def set_all_created_model_as_published(aps, schema_editor):
    PostCls = aps.get_model('showcase', 'Post')
    PostCls.objects.update(status=Post.PUBLISHED)


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0002_post_status'),
    ]

    operations = [
        migrations.RunPython(set_all_created_model_as_published),
    ]
